version: '3'
services:
  app:
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails server -b 0.0.0.0"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db:5432/myproject_development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://elasticsearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myproject_development
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "myproject_development", "-U", "myuser"]
      interval: 5s
      timeout: 2s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
    environment:
    - discovery.type=single-node
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
