version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    environment:
      - DATABASE_URL=postgres://db:5432/myproject_development
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myproject_development
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
